server:
  port: 1181
  servlet:
    context-path: /

spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/blueberry?useUnicode=true&characterEncoding=UTF-8&useSSL=false&useTimezone=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true&autoReconnect=true
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root
      # 初始化时建立物理连接的个数
      initial-size: 5
      # 最大连接池数量
      max-active: 30
      # 最小连接池数量
      min-idle: 5
      # 获取连接时最大等待时间，单位毫秒
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 连接保持空闲而不被驱逐的最小时间
      min-evictable-idle-time-millis: 300000
      # 用来检测连接是否有效的sql，要求是一个查询语句
      validation-query: SELECT 1 FROM DUAL
      # 建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      test-while-idle: true
      # 申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      test-on-borrow: false
      # 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      test-on-return: false
      # 是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭。
      pool-prepared-statements: true
      # 要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。
      max-pool-prepared-statement-per-connection-size: 50
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计
      filters: stat,wall
      # 合并多个DruidDataSource的监控数据
      use-global-data-source-stat: true
      filter:
        stat:
          merge-sql: true
          log-slow-sql: true

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: root
    timeout: 3000
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1

  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

  thymeleaf:
    cache: false
    check-template: false
    encoding: utf-8
    mode: HTML
    prefix: classpath:templates/
    servlet:
      content-type: text/html
  mvc:
    view:
      prefix: templates/
      suffix: .html

mybatis:
  type-aliases-package: com.jiafly.blueberry.domain.model
  mapper-locations: classpath:mapper/**/*.xml

